title: 前端开发文档
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  input: GFM

#permalink:
permalink: pretty
baseurl: ""
# timeago 插件
gems:
  - jekyll-timeago
jekyll_timeago:
  depth: 1 # Level of detail
  today: '今天'
  yesterday: '昨天'
  tomorrow: '明天'
  and: '零'
  suffix: '前'
  prefix: '更新于'
  suffix_future: ''
  prefix_future: 'in'
  years: '年'
  year: 'year'
  months: '个月'
  month: '月'
  weeks: '周'
  week: '周'
  days: '天'
  day: '天'

github:
  repo: https://github.com/fe-knowledge/fedguide.github.io.git
